export const initialInventoryData = [
  {
    id: 1,
    name: "Item 1",
    sku: "SKU001",
    quantity: 100,
    warehouse: "Warehouse A",
  },
  {
    id: 2,
    name: "Item 2",
    sku: "SKU002",
    quantity: 200,
    warehouse: "Warehouse B",
  },
  {
    id: 3,
    name: "Item 3",
    sku: "SKU003",
    quantity: 150,
    warehouse: "Warehouse C",
  },
  {
    id: 4,
    name: "Item 4",
    sku: "SKU004",
    quantity: 120,
    warehouse: "Warehouse D",
  },
  {
    id: 5,
    name: "Item 5",
    sku: "SKU005",
    quantity: 180,
    warehouse: "Warehouse E",
  },
  {
    id: 6,
    name: "Item 6",
    sku: "SKU006",
    quantity: 220,
    warehouse: "Warehouse F",
  },
  {
    id: 7,
    name: "Item 7",
    sku: "SKU007",
    quantity: 90,
    warehouse: "Warehouse G",
  },
  {
    id: 8,
    name: "Item 8",
    sku: "SKU008",
    quantity: 250,
    warehouse: "Warehouse H",
  },
  {
    id: 9,
    name: "Item 9",
    sku: "SKU009",
    quantity: 170,
    warehouse: "Warehouse I",
  },
  {
    id: 10,
    name: "Item 10",
    sku: "SKU010",
    quantity: 140,
    warehouse: "Warehouse J",
  },
  {
    id: 11,
    name: "Item 11",
    sku: "SKU011",
    quantity: 130,
    warehouse: "Warehouse K",
  },
  {
    id: 12,
    name: "Item 12",
    sku: "SKU012",
    quantity: 190,
    warehouse: "Warehouse L",
  },
  {
    id: 13,
    name: "Item 13",
    sku: "SKU013",
    quantity: 210,
    warehouse: "Warehouse M",
  },
  {
    id: 14,
    name: "Item 14",
    sku: "SKU014",
    quantity: 160,
    warehouse: "Warehouse N",
  },
  {
    id: 15,
    name: "Item 15",
    sku: "SKU015",
    quantity: 230,
    warehouse: "Warehouse O",
  },
];

// Initial data for Shipments
export const initialShipmentsData = [
  {
    id: 1,
    origin: "Location A",
    destination: "Location B",
    status: "In Transit",
    estimatedDelivery: "2024-05-25",
  },
  {
    id: 2,
    origin: "Location C",
    destination: "Location D",
    status: "Delivered",
    estimatedDelivery: "2024-05-20",
  },
  {
    id: 3,
    origin: "Location E",
    destination: "Location F",
    status: "In Transit",
    estimatedDelivery: "2024-05-23",
  },
  {
    id: 4,
    origin: "Location G",
    destination: "Location H",
    status: "Delayed",
    estimatedDelivery: "2024-06-02",
  },
  {
    id: 5,
    origin: "Location I",
    destination: "Location J",
    status: "Delivered",
    estimatedDelivery: "2024-05-18",
  },
  {
    id: 6,
    origin: "Location K",
    destination: "Location L",
    status: "In Transit",
    estimatedDelivery: "2024-05-30",
  },
  {
    id: 7,
    origin: "Location M",
    destination: "Location N",
    status: "In Transit",
    estimatedDelivery: "2024-06-05",
  },
  {
    id: 8,
    origin: "Location O",
    destination: "Location P",
    status: "Delivered",
    estimatedDelivery: "2024-05-15",
  },
  {
    id: 9,
    origin: "Location Q",
    destination: "Location R",
    status: "Delayed",
    estimatedDelivery: "2024-06-10",
  },
  {
    id: 10,
    origin: "Location S",
    destination: "Location T",
    status: "In Transit",
    estimatedDelivery: "2024-06-08",
  },
];

// Initial data for Suppliers
export const initialSuppliersData = [
  {
    id: 1,
    name: "Supplier A",
    contactPerson: "John Doe",
    phone: "123-456-7890",
    email: "john@example.com",
  },
  {
    id: 2,
    name: "Supplier B",
    contactPerson: "Jane Smith",
    phone: "987-654-3210",
    email: "jane@example.com",
  },
  {
    id: 3,
    name: "Supplier C",
    contactPerson: "Michael Johnson",
    phone: "456-789-0123",
    email: "michael@example.com",
  },
  {
    id: 4,
    name: "Supplier D",
    contactPerson: "Emily Brown",
    phone: "789-012-3456",
    email: "emily@example.com",
  },
  {
    id: 5,
    name: "Supplier E",
    contactPerson: "David Wilson",
    phone: "012-345-6789",
    email: "david@example.com",
  },
  {
    id: 6,
    name: "Supplier F",
    contactPerson: "Sophia Martinez",
    phone: "345-678-9012",
    email: "sophia@example.com",
  },
  {
    id: 7,
    name: "Supplier G",
    contactPerson: "William Anderson",
    phone: "678-901-2345",
    email: "william@example.com",
  },
  {
    id: 8,
    name: "Supplier H",
    contactPerson: "Olivia Garcia",
    phone: "901-234-5678",
    email: "olivia@example.com",
  },
  {
    id: 9,
    name: "Supplier I",
    contactPerson: "James Rodriguez",
    phone: "234-567-8901",
    email: "james@example.com",
  },
  {
    id: 10,
    name: "Supplier J",
    contactPerson: "Emma Lopez",
    phone: "567-890-1234",
    email: "emma@example.com",
  },
  {
    id: 11,
    name: "Supplier K",
    contactPerson: "Noah Perez",
    phone: "890-123-4567",
    email: "noah@example.com",
  },
  {
    id: 12,
    name: "Supplier L",
    contactPerson: "Isabella Taylor",
    phone: "123-456-7890",
    email: "isabella@example.com",
  },
  {
    id: 13,
    name: "Supplier M",
    contactPerson: "Liam Hernandez",
    phone: "456-789-0123",
    email: "liam@example.com",
  },
  {
    id: 14,
    name: "Supplier N",
    contactPerson: "Ava Martinez",
    phone: "789-012-3456",
    email: "ava@example.com",
  },
  {
    id: 15,
    name: "Supplier O",
    contactPerson: "Mason Young",
    phone: "012-345-6789",
    email: "mason@example.com",
  },
];
